### ISSUE TITLE
code snippet color not suitable

### ISSUE THREAD

**Issue by XHMM** [fullstackio/30-days-of-vue#1]
Found in [day3](https://www.fullstack.io/30-days-of-vue/day-03-the-vue-instance---data-driven-applications/), maybe should change to white color

![image](https://user-images.githubusercontent.com/24786522/51010085-ae476f80-158d-11e9-83cd-b92465875a71.png)

**Comment by djirdehh** [comment]
Thanks @XHMM! Will take a look 👀

**Comment by djirdehh** [comment]
I think the compiler acted a little weirdly with the syntax of the code snippet we intended to show. I've made a minor change that should resolve this with the next deployment 👍 .

cc @jashmenn
