### ISSUE TITLE
Insight hooks

### ISSUE THREAD

**Issue by ErDhruveshAkhani** [fullstackio/30-days-of-vue#3]
Hello Hassan,
First of all thank you so much for wonderful explanation of very small topics of vue js.
While reading  '30-days-of-vue' on day-10 you have mentioned life hooks for created and mounted.As i gone though documentation of vue [vue hooks](https://vuejs.org/v2/guide/instance.html#Instance-Lifecycle-Hooks) there are many other hooks are also present .
It will be great to read other hooks with your explanation .
**Thanks** 
**Dhruvesh Akhani**
**Software Engineer**

**Comment by djirdehh** [comment]
Apologies for seeing this so late!

Thanks for the kind words Dhruvesh! Means a lot. Unfortunately, I don't have any immediate plans on adding more documentation on the other Vue Life Cycle hooks so will close this for now :).
