### ISSUE TITLE
Data must be a function

### ISSUE THREAD

**Issue by scottpage** [fullstackio/30-days-of-vue#4]
Great series!  Just an FYI, data must be an object returned by a function, but in your examples data is only an object.

[https://vuejs.org/v2/guide/components.html#data-Must-Be-a-Function](url)

This:
```
data() { // or data: function() {
  return {
    someValue: 'test'
  }
}
```

Not this:
```
data: {
  someValue: 'test'
}
```

**Comment by djirdehh** [comment]
Hey @scottpage! Thanks for the issue and apologies for only seeing this now.

I believe `data()` _must_ be a function only when `data` is being specified in _components_. In instantiating `data` within a Vue instance, it's possible for it to be an object.

https://vuejs.org/v2/api/#Options-Data

Thank you again!
